kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.30.10
  extraPortMappings:
  - containerPort: 30080
    hostPort: 9080
    protocol: TCP
- role: worker
  image: kindest/node:v1.30.10
  extraPortMappings:
  - containerPort: 30080
    hostPort: 9081
    protocol: TCP
